### ISSUE TITLE
There is no link to live app in readme

### ISSUE THREAD

**Issue by vivek80801** [gorgorgordon/gorgorgordon.github.io#1]
This project is live on internet. But in [README.md](https://github.com/gorgorgordon/gorgorgordon.github.io/blob/main/README.md, "go to README.md"). There is no link to live app. You can see this app [here](https://gorgorgordon.github.io/, "Go to live App")

**Comment by gorgorgordon** [comment]
Thanks for your advice, Vivek~

Is it good now?

**Comment by vivek80801** [comment]
I think. It should be

```diff

- https://gorgorgordon.github.io

+ [Gordon's To-do List](https://gorgorgordon.github.io, "See Gordon's To-do List")
```

**Comment by gorgorgordon** [comment]
Nice application of markdown~

Edited accordingly, thanks Vivek~

**Comment by vivek80801** [comment]
This was my mistake. Sorry.

**comma** is breaking link.

```diff
- [Gordon's To-do List](https://gorgorgordon.github.io, "See Gordon's To-do List")

+ [Gordon's To-do List](https://gorgorgordon.github.io "See Gordon's To-do List")
```
[Gordon's To-do List](https://gorgorgordon.github.io "See Gordon's To-do List")

**Comment by gorgorgordon** [comment]
Oh yes~ I didn't test too haha

Thanks again~
